<?php

/**
 * Searchable pages for global search (Cmd+K).
 * Synced to Meilisearch via SearchService::syncPagesToIndex().
 * Add new pages here and run: php artisan search:reindex pages
 *
 * @see docs/ai/recipes/add-searchable-page.md
 */
return [
    // User pages (all users)
    [
        'id' => 'mail',
        'title' => 'Inbox',
        'url' => '/mail',
        'admin_only' => false,
        'content' => 'inbox email mail messages',
    ],
    [
        'id' => 'notifications',
        'title' => 'Notifications',
        'url' => '/notifications',
        'admin_only' => false,
        'content' => 'alerts messages notifications',
    ],
    [
        'id' => 'user-preferences',
        'title' => 'User Preferences',
        'url' => '/user/preferences',
        'admin_only' => false,
        'content' => 'settings profile preferences',
    ],
    [
        'id' => 'user-profile',
        'title' => 'User Profile',
        'url' => '/user/profile',
        'admin_only' => false,
        'content' => 'account avatar profile',
    ],
    [
        'id' => 'user-security',
        'title' => 'User Security',
        'subtitle' => 'Password, 2FA, passkeys, connected accounts',
        'url' => '/user/security',
        'admin_only' => false,
        'content' => 'password 2fa two-factor mfa passkeys sso connected accounts security',
    ],
    // Configuration pages (admin only)
    [
        'id' => 'config-system',
        'title' => 'Configuration > System',
        'subtitle' => 'Application-wide settings',
        'url' => '/configuration/system',
        'admin_only' => true,
        'content' => 'app general system settings',
    ],
    [
        'id' => 'config-branding',
        'title' => 'Configuration > Theme & Branding',
        'subtitle' => 'Visual customization',
        'url' => '/configuration/branding',
        'admin_only' => true,
        'content' => 'theme palette logo branding visual',
    ],
    [
        'id' => 'config-users',
        'title' => 'Configuration > Users',
        'subtitle' => 'Manage application users',
        'url' => '/configuration/users',
        'admin_only' => true,
        'content' => 'manage users admin user list',
    ],
    [
        'id' => 'config-groups',
        'title' => 'Configuration > Groups',
        'subtitle' => 'User groups and permissions',
        'url' => '/configuration/groups',
        'admin_only' => true,
        'content' => 'groups permissions roles members',
    ],
    [
        'id' => 'config-security',
        'title' => 'Configuration > Security',
        'subtitle' => 'Auth and security settings',
        'url' => '/configuration/security',
        'admin_only' => true,
        'content' => 'auth 2fa password reset TOTP email verification',
    ],
    [
        'id' => 'config-sso',
        'title' => 'Configuration > SSO',
        'subtitle' => 'Single sign-on providers',
        'url' => '/configuration/sso',
        'admin_only' => true,
        'content' => 'oauth google github gitlab microsoft azure ad apple discord OIDC SAML login',
    ],
    [
        'id' => 'config-api',
        'title' => 'Configuration > Webhooks',
        'subtitle' => 'Outgoing webhook endpoints',
        'url' => '/configuration/api',
        'admin_only' => true,
        'content' => 'webhooks API events automation',
    ],
    [
        'id' => 'user-api-keys',
        'title' => 'Security > API Keys',
        'subtitle' => 'Manage personal API keys',
        'url' => '/user/security',
        'admin_only' => false,
        'content' => 'api keys graphql programmatic access bearer token rotate revoke',
    ],
    [
        'id' => 'config-notifications',
        'title' => 'Configuration > Notifications',
        'subtitle' => 'Configure notification channels',
        'url' => '/configuration/notifications',
        'admin_only' => true,
        'content' => 'channels telegram discord slack signal twilio vonage SNS webpush FCM ntfy matrix',
    ],
    [
        'id' => 'config-email',
        'title' => 'Configuration > Email',
        'subtitle' => 'Email delivery configuration',
        'url' => '/configuration/email',
        'admin_only' => true,
        'content' => 'smtp mailgun sendgrid AWS SES postmark TLS encryption mail',
    ],
    [
        'id' => 'config-email-templates',
        'title' => 'Configuration > Email Templates',
        'subtitle' => 'Customize system emails',
        'url' => '/configuration/email-templates',
        'admin_only' => true,
        'content' => 'templates email subject body',
    ],
    [
        'id' => 'config-notification-templates',
        'title' => 'Configuration > Notification Templates',
        'subtitle' => 'Per-type push, in-app, chat templates',
        'url' => '/configuration/notification-templates',
        'admin_only' => true,
        'content' => 'notification templates push inapp chat per-type',
    ],
    [
        'id' => 'config-changelog',
        'title' => 'Configuration > Changelog',
        'subtitle' => 'Version history and release notes',
        'url' => '/configuration/changelog',
        'admin_only' => false,
        'content' => 'changelog version release notes updates what\'s new history',
    ],
    [
        'id' => 'config-ai',
        'title' => 'Configuration > AI / LLM',
        'subtitle' => 'LLM providers and models',
        'url' => '/configuration/ai',
        'admin_only' => true,
        'content' => 'Claude Anthropic OpenAI GPT ChatGPT Google Gemini Vertex AI AWS Amazon Bedrock Ollama local models Azure OpenAI Groq Mistral Llama API key model selection council mode multi-provider primary fallback timeout',
    ],
    [
        'id' => 'config-storage',
        'title' => 'Configuration > Storage',
        'subtitle' => 'File storage configuration',
        'url' => '/configuration/storage',
        'admin_only' => true,
        'content' => 'S3 AWS Amazon bucket local disk filesystem upload size limit file types allowed extensions region endpoint credentials',
    ],
    [
        'id' => 'config-search',
        'title' => 'Configuration > Search',
        'subtitle' => 'Manage search indexes',
        'url' => '/configuration/search',
        'admin_only' => true,
        'content' => 'meilisearch index reindex search',
    ],
    [
        'id' => 'config-audit',
        'title' => 'Configuration > Audit Log',
        'subtitle' => 'View system activity logs',
        'url' => '/configuration/audit',
        'admin_only' => true,
        'content' => 'logs activity audit',
    ],
    [
        'id' => 'config-logs',
        'title' => 'Configuration > Application Logs',
        'subtitle' => 'Real-time console log viewer',
        'url' => '/configuration/logs',
        'admin_only' => true,
        'content' => 'console log viewer',
    ],
    [
        'id' => 'config-log-retention',
        'title' => 'Configuration > Log retention',
        'subtitle' => 'Retention and cleanup config',
        'url' => '/configuration/log-retention',
        'admin_only' => true,
        'content' => 'retention cleanup logs',
    ],
    [
        'id' => 'config-jobs',
        'title' => 'Configuration > Jobs',
        'subtitle' => 'Monitor scheduled jobs',
        'url' => '/configuration/jobs',
        'admin_only' => true,
        'content' => 'scheduled queue tasks jobs',
    ],
    [
        'id' => 'config-backup',
        'title' => 'Configuration > Backup & Restore',
        'subtitle' => 'Manage system backups',
        'url' => '/configuration/backup',
        'admin_only' => true,
        'content' => 'restore export backup S3 SFTP Google Drive encryption retention schedule',
    ],
    [
        'id' => 'config-usage',
        'title' => 'Configuration > Usage & Costs',
        'subtitle' => 'Integration usage analytics and cost tracking',
        'url' => '/configuration/usage',
        'admin_only' => true,
        'permission' => 'usage.view',
        'content' => 'usage cost analytics tokens llm billing spending integrations budget',
    ],
    [
        'id' => 'config-notification-deliveries',
        'title' => 'Configuration > Delivery Log',
        'subtitle' => 'Notification delivery attempts and failures',
        'url' => '/configuration/notification-deliveries',
        'admin_only' => true,
        'permission' => 'notification_deliveries.view',
        'content' => 'notification delivery log failed retry channel rate limit webhook queue',
    ],
    [
        'id' => 'config-stripe',
        'title' => 'Configuration > Stripe',
        'subtitle' => 'Payment processing configuration',
        'url' => '/configuration/stripe',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'stripe payments connect billing webhooks api keys platform',
    ],
    [
        'id' => 'config-payments',
        'title' => 'Configuration > Payment History',
        'subtitle' => 'View payment transactions',
        'url' => '/configuration/payments',
        'admin_only' => true,
        'permission' => 'payments.view',
        'content' => 'payments transactions history billing invoices',
    ],
    [
        'id' => 'config-graphql',
        'title' => 'Configuration > GraphQL API',
        'subtitle' => 'GraphQL settings, API keys, and usage stats',
        'url' => '/configuration/graphql',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'graphql api keys settings rate limit introspection query depth complexity cors usage stats',
    ],

    // Email Hosting
    [
        'id' => 'mail',
        'title' => 'Mail',
        'subtitle' => 'Email inbox and client',
        'url' => '/mail',
        'admin_only' => false,
        'content' => 'email inbox compose send receive mail messages threads',
    ],
    [
        'id' => 'contacts',
        'title' => 'Contacts',
        'subtitle' => 'Manage email contacts',
        'url' => '/contacts',
        'admin_only' => false,
        'content' => 'contacts address book people email autocomplete merge',
    ],
    [
        'id' => 'mail-settings',
        'title' => 'Mail Settings',
        'subtitle' => 'Email rules, spam filter, and import',
        'url' => '/mail/settings',
        'admin_only' => false,
        'content' => 'mail settings preferences email rules spam import',
    ],
    [
        'id' => 'mail-settings-rules',
        'title' => 'Mail Settings > Rules',
        'subtitle' => 'Automatic email processing rules',
        'url' => '/mail/settings/rules',
        'admin_only' => false,
        'content' => 'email rules filters auto label archive forward mark read spam',
    ],
    [
        'id' => 'mail-settings-spam',
        'title' => 'Mail Settings > Spam Filter',
        'subtitle' => 'Personal allow and block sender lists',
        'url' => '/mail/settings/spam',
        'admin_only' => false,
        'content' => 'spam filter allow block list sender domain email personal',
    ],
    [
        'id' => 'mail-settings-import',
        'title' => 'Mail Settings > Import Emails',
        'subtitle' => 'Import mbox or eml files',
        'url' => '/mail/settings/import',
        'admin_only' => false,
        'content' => 'import mbox eml upload email file mailbox',
    ],
    [
        'id' => 'config-email-accounts',
        'title' => 'Configuration > Provider Accounts',
        'subtitle' => 'Manage email provider credentials',
        'url' => '/configuration/email-accounts',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'provider accounts credentials mailgun ses postmark resend mailersend smtp2go email api key',
    ],
    [
        'id' => 'config-email-domains',
        'title' => 'Configuration > Email Domains',
        'subtitle' => 'Manage email domains',
        'url' => '/configuration/email-domains',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'domain dns verify email hosting mailgun',
    ],
    [
        'id' => 'config-mailboxes',
        'title' => 'Configuration > Mailboxes',
        'subtitle' => 'Manage email addresses',
        'url' => '/configuration/mailboxes',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'mailbox address catchall email inbox',
    ],
    [
        'id' => 'config-spam-filter',
        'title' => 'Configuration > Global Spam Filter',
        'subtitle' => 'System-wide allow and block lists (applies to all users)',
        'url' => '/configuration/spam-filter',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'spam filter allow block list sender domain email global system',
    ],

    // Help articles — Email AI
    [
        'id' => 'help-email-ai-features',
        'title' => 'Help: AI Email Features',
        'subtitle' => 'Help article',
        'url' => 'help:email-ai-features',
        'admin_only' => false,
        'content' => 'ai llm email summary summarize labels categorize priority inbox smart replies thread',
    ],

    // -----------------------------------------------------------------------
    // Help articles (user-visible, no permission required)
    // -----------------------------------------------------------------------
    [
        'id' => 'help-welcome',
        'title' => 'Help: Welcome to selfmx',
        'subtitle' => 'Help article',
        'url' => 'help:welcome',
        'admin_only' => false,
        'content' => 'getting started overview introduction help guide features authentication',
    ],
    [
        'id' => 'help-navigation',
        'title' => 'Help: Navigating the App',
        'subtitle' => 'Help article',
        'url' => 'help:navigation',
        'admin_only' => false,
        'content' => 'menu sidebar navigate inbox mail profile keyboard shortcuts',
    ],
    [
        'id' => 'help-search',
        'title' => 'Help: Using Search',
        'subtitle' => 'Help article',
        'url' => 'help:search',
        'admin_only' => false,
        'content' => 'search find filter cmd+k ctrl+k help articles',
    ],
    [
        'id' => 'help-theme-appearance',
        'title' => 'Help: Theme & Appearance',
        'subtitle' => 'Help article',
        'url' => 'help:theme-appearance',
        'admin_only' => false,
        'content' => 'theme dark light appearance customization preferences',
    ],
    [
        'id' => 'help-changelog',
        'title' => 'Help: Changelog & Version History',
        'subtitle' => 'Help article',
        'url' => 'help:changelog',
        'admin_only' => false,
        'content' => 'changelog version release notes updates history what is new',
    ],
    [
        'id' => 'help-profile',
        'title' => 'Help: Managing Your Profile',
        'subtitle' => 'Help article',
        'url' => 'help:profile',
        'admin_only' => false,
        'content' => 'profile account avatar display name email settings',
    ],
    [
        'id' => 'help-password',
        'title' => 'Help: Changing Your Password',
        'subtitle' => 'Help article',
        'url' => 'help:password',
        'admin_only' => false,
        'content' => 'password security change reset requirements',
    ],
    [
        'id' => 'help-two-factor',
        'title' => 'Help: Two-Factor Authentication',
        'subtitle' => 'Help article',
        'url' => 'help:two-factor',
        'admin_only' => false,
        'content' => '2fa two-factor authenticator TOTP recovery codes security',
    ],
    [
        'id' => 'help-passkeys',
        'title' => 'Help: Using Passkeys',
        'subtitle' => 'Help article',
        'url' => 'help:passkeys',
        'admin_only' => false,
        'content' => 'passkey webauthn biometric fingerprint face sign in',
    ],
    [
        'id' => 'help-sessions',
        'title' => 'Help: Managing Sessions',
        'subtitle' => 'Help article',
        'url' => 'help:sessions',
        'admin_only' => false,
        'content' => 'session devices logout revoke active sessions',
    ],
    [
        'id' => 'help-notification-settings',
        'title' => 'Help: Notification Settings',
        'subtitle' => 'Help article',
        'url' => 'help:notification-settings',
        'admin_only' => false,
        'content' => 'notifications alerts preferences in-app email push',
    ],

    // -----------------------------------------------------------------------
    // Help articles (permission-gated)
    // -----------------------------------------------------------------------

    // Administration (settings.view)
    [
        'id' => 'help-admin-overview',
        'title' => 'Help: Administration Overview',
        'subtitle' => 'Help article',
        'url' => 'help:admin-overview',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'admin settings configuration user management audit logs',
    ],
    [
        'id' => 'help-branding',
        'title' => 'Help: Branding & Customization',
        'subtitle' => 'Help article',
        'url' => 'help:branding',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'branding logo colors theme visual app name',
    ],

    // User Management (users.view)
    [
        'id' => 'help-user-management',
        'title' => 'Help: User Management',
        'subtitle' => 'Help article',
        'url' => 'help:user-management',
        'admin_only' => true,
        'permission' => 'users.view',
        'content' => 'users admin accounts roles disable delete manage',
    ],
    [
        'id' => 'help-groups-management',
        'title' => 'Help: User Groups & Permissions',
        'subtitle' => 'Help article',
        'url' => 'help:groups-management',
        'admin_only' => true,
        'permission' => 'groups.view',
        'content' => 'groups permissions roles members access control matrix',
    ],

    // Security & Access (settings.view)
    [
        'id' => 'help-security-settings',
        'title' => 'Help: Security Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:security-settings',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'security policy 2fa password session SSO admin',
    ],
    [
        'id' => 'help-sso-configuration',
        'title' => 'Help: SSO Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:sso-configuration',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'sso oauth google github single sign-on providers linking',
    ],
    [
        'id' => 'help-api-webhooks',
        'title' => 'Help: Webhooks',
        'subtitle' => 'Help article',
        'url' => 'help:api-webhooks',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'webhooks automation integration HMAC signature events',
    ],
    [
        'id' => 'help-api-keys',
        'title' => 'Help: API Keys',
        'subtitle' => 'Help article',
        'url' => 'help:api-keys',
        'admin_only' => false,
        'content' => 'api keys graphql bearer token rotate revoke programmatic access security',
    ],

    // Communications (settings.view)
    [
        'id' => 'help-email-configuration',
        'title' => 'Help: Email Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:email-configuration',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'email smtp mailgun sendgrid AWS SES postmark delivery',
    ],
    [
        'id' => 'help-email-templates',
        'title' => 'Help: Email Templates',
        'subtitle' => 'Help article',
        'url' => 'help:email-templates',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'email templates variables customize subject body',
    ],
    [
        'id' => 'help-notification-channels',
        'title' => 'Help: Notification Channels',
        'subtitle' => 'Help article',
        'url' => 'help:notification-channels',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'notification channels telegram discord slack sms push web admin configure enable',
    ],
    [
        'id' => 'help-notification-templates',
        'title' => 'Help: Notification Templates',
        'subtitle' => 'Help article',
        'url' => 'help:notification-templates',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'notification templates push inapp chat customize variables per-type',
    ],
    [
        'id' => 'help-novu-configuration',
        'title' => 'Help: Novu Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:novu-configuration',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'novu notification infrastructure workflows inbox optional',
    ],

    // Integrations (settings.view)
    [
        'id' => 'help-ai-llm-settings',
        'title' => 'Help: AI / LLM Settings',
        'subtitle' => 'Help article',
        'url' => 'help:ai-llm-settings',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'ai llm openai anthropic claude models providers',
    ],
    [
        'id' => 'help-storage-settings',
        'title' => 'Help: Storage Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:storage-settings',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'storage s3 disk upload files provider local cloud azure gcs minio',
    ],
    [
        'id' => 'help-search-config',
        'title' => 'Help: Search Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:search-config',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'search meilisearch indexing reindex admin troubleshooting',
    ],

    // Logs & Monitoring
    [
        'id' => 'help-audit-logs',
        'title' => 'Help: Audit Log',
        'subtitle' => 'Help article',
        'url' => 'help:audit-logs',
        'admin_only' => true,
        'permission' => 'audit.view',
        'content' => 'audit activity tracking events filter export live streaming',
    ],
    [
        'id' => 'help-application-logs',
        'title' => 'Help: Application Logs',
        'subtitle' => 'Help article',
        'url' => 'help:application-logs',
        'admin_only' => true,
        'permission' => 'logs.view',
        'content' => 'application logs console viewer errors debug export correlation',
    ],
    [
        'id' => 'help-log-retention',
        'title' => 'Help: Log Retention',
        'subtitle' => 'Help article',
        'url' => 'help:log-retention',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'retention cleanup logs storage days automatic',
    ],
    [
        'id' => 'help-scheduled-jobs',
        'title' => 'Help: Scheduled Jobs',
        'subtitle' => 'Help article',
        'url' => 'help:scheduled-jobs',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'jobs scheduler queue tasks cron run manual backup cleanup',
    ],

    // Usage & Costs (usage.view)
    [
        'id' => 'help-usage-costs',
        'title' => 'Help: Usage & Costs',
        'subtitle' => 'Help article',
        'url' => 'help:usage-costs',
        'admin_only' => true,
        'permission' => 'usage.view',
        'content' => 'usage cost analytics budget billing llm email sms storage trends export',
    ],

    // Backup & Data (backups.view)
    [
        'id' => 'help-backup-settings',
        'title' => 'Help: Backup Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:backup-settings',
        'admin_only' => true,
        'permission' => 'backups.view',
        'content' => 'backup restore admin data automatic manual schedule retention',
    ],

    // Payments (settings.view / payments.view)
    [
        'id' => 'help-stripe-configuration',
        'title' => 'Help: Stripe Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:stripe-configuration',
        'admin_only' => true,
        'permission' => 'settings.view',
        'content' => 'stripe payments connect billing api keys webhook platform onboarding test live',
    ],
    [
        'id' => 'help-payment-history',
        'title' => 'Help: Payment History',
        'subtitle' => 'Help article',
        'url' => 'help:payment-history',
        'admin_only' => true,
        'permission' => 'payments.view',
        'content' => 'payments transactions history billing refunds amount status admin',
    ],
];
